name: Commit cheat

on:
  workflow_dispatch:

  schedule:
  - cron: "0 */5 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify README.md
        run: |
          curl -H "Accept: text/plain" https://icanhazdadjoke.com | sed 's/^/## /' > README.md

      - name: Commit changes
        env:
          GIT_AUTHOR_EMAIL: "niteshraj231@outlook.com"
          GIT_AUTHOR_NAME: "Nitesh"
          GIT_COMMITTER_EMAIL: "niteshraj231@outlook.com"
          GIT_COMMITTER_NAME: "Nitesh"
        run: |
          git config --global --add safe.directory /github/workspace
          git add README.md
          git commit -sm "$(curl -s https://raw.githubusercontent.com/ngerakines/commitment/main/commit_messages.txt | shuf -n 1) \nChange ID: $(uuidgen)"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.TOKEN_GITHUB }}