name: Commit cheat

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *" # Every 5 hours

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify README.md
        run: |
          curl -H "Accept: text/plain" https://icanhazdadjoke.com | sed 's/^/## /' > README.md

      - name: Commit changes
        env:
          GIT_AUTHOR_EMAIL: "niteshraj231@outlook.com"
          GIT_AUTHOR_NAME: "Nitesh"
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"
          git add README.md
          COMMIT_MSG=$(curl -s https://raw.githubusercontent.com/ngerakines/commitment/main/commit_messages.txt | shuf -n 1)
          echo "$COMMIT_MSG" > commit_message.txt
          echo "" >> commit_message.txt
          echo "Change-Id: $(uuidgen)" >> commit_message.txt
          echo "Signed-off-by: Nitesh <niteshraj231@outlook.com>" >> commit_message.txt
          git commit -F commit_message.txt
          rm commit_message.txt

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}